@startuml

== Logging ==

Client -> Server: LOG
Client <-- Server: LOG (success / failure)

== Getting list of games ==

Client -> Server: LIS
Client <-- Server: LIS (list of games)

== Creating/Joining game ==

Client -> Server: NEW (setting) | PLY (game ID)
Client <-- Server: GAM (game ID)

== Playing game ==

...retrieving game data...

Client <-- Server: MOV (game ID, piece, x, y)

...user actions\nand other players actions...

Client --> Server: MOV (game ID, piece, x, y)
Client <-- Server: MOV (game ID, piece, x, y)

...eventually...

Client <-- Server: WIN (game ID)

...exit game...

Client -> Server: OFF

...close connection...

Client -> Server: BYE

@enduml
