@startuml

== Logging ==

Client -> Server: LIN
Client <-- Server: LIN (success / failure)

== Getting list of games ==

Client -> Server: GLI
Client <-- Server: GLI (list of games)

== Creating/Joining game ==

Client -> Server: GNW (setting) | GIN (game ID)
Client <-- Server: GAM (game ID)

== Playing game ==

...retrieving game data...

Client <-- Server: GMV (game ID, piece, x, y)

...user actions\nand other players actions...

Client --> Server: GMV (game ID, piece, x, y)
Client <-- Server: GMV (game ID, piece, x, y)

...eventually...

Client <-- Server: GWI (game ID)

...exit game...

Client -> Server: GOF

...log out...

Client -> Server: LOF

...close connection...

Client -> Server: BYE

@enduml
