@startuml
title Session (client view)

[*] --> connected

state "Connected" as connected
connected --> logged:LIN
connected --> not_connected:BYE*

state "Logged" as logged
logged --> not_connected:BYE*
logged --> game:GNW,\nGIN
logged --> logged:GLI
logged --> connected:LOF

state "In game" as game
game --> not_connected:BYE*
game --> logged:GOF
game --> game:GMV

state "Disconnected" as not_connected
not_connected --> [*]
@enduml
